title: "Owen H. Funk"
email: owenfunk@gmail.com
description: "Personal website of scientist Owen H. Funk"
baseurl: "" # Leave empty for GitHub Pages
url: "https://ohfunk.github.io" # Replace with your GitHub Pages URL
theme: minima
author: "Owen H. Funk"
