title: "Funk Lab"
email: ofunk@uwyo.edu
description: "How cell fusion shapes gene expression during development."
baseurl: ""
url: "https://ohfunk.github.io"
author: "Owen H. Funk, PhD"
markdown: kramdown
permalink: pretty
exclude: [Gemfile, Gemfile.lock]
