title: "Owen H. Funk"
email: your.email@example.com
description: "Personal website of scientist Owen H. Funk"
baseurl: "" # Leave empty for GitHub Pages
url: "https://yourusername.github.io" # Replace with your GitHub Pages URL
theme: minima
author: "Owen H. Funk"
